### ISSUE TITLE
Proposal: Switch to github actions

### ISSUE THREAD

**Issue by mwz** [sksamuel/scapegoat#306]
I'd like to propose that we switch from Travis to Github actions and set up the following:

- [X] PR checks (#318):
	- run tests against a matrix of Scala versions (similarly to what is currently done in travis) and in addition:
	- publishLocal and execute Scapegoat against itself (and fail on errors) as mentioned in #305 
	- use codecov to post coverage info
- [X] post coverage info to codecov on master (#323)
- [x] publish snapshots every time a PR is merged to master; [sbt-ci-release](https://github.com/olafurpg/sbt-ci-release) works like a charm - I've set it up recently for scalastyle [here](https://github.com/beautiful-scala/scalastyle/blob/master/.github/workflows/release.yml) (#327)
- [x] automate the release based on a pushed tag (also works great, see the same github action above) (#327)

**Comment by sksamuel** [comment]
I use github actions elsewhere and am very happy with it.
See kotest / hoplite

**Comment by mwz** [comment]
hey @mccartney, do you have any thoughts on this? Are you happy with that approach?

**Comment by mccartney** [comment]
I am fine. I don't have any experience with Github Actions (happy to learn them though).

I think it's mostly about the publish process, which I don't know how it works for this project.

All in all - go ahead. I have no input here. I appreciate your work!

**Comment by sksamuel** [comment]
What I've done elsewhere is have a snapshot publish for every commit to
master, and leave release publications manual.

**Comment by mwz** [comment]
I'm planning to have the release automated on a tag being pushed, so that any maintainer with push permissions can push a tag and trigger a new release. Hopefully, that can lead to more frequent releases.

**Comment by sksamuel** [comment]
That would be nice, I've not used sbt-ci-releases.
I tend to release all my projects by hand.
